make_cmds = [
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-fopenmp", "-I/usr/include/apr-1.0", "binarytrees.c++", "-o", "binarytrees.c++.o"],
   ["binarytrees.c++.o", "-o", "binarytrees", "-fopenmp", "-lapr-1"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-std=c++11", "-fopenmp", "fannkuchredux.c++", "-o", "fannkuchredux.c++.o"],
   ["fannkuchredux.c++.o", "-o", "fannkuchredux", "-fopenmp"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-mfpmath=sse", "-msse3", "-std=c++17", "fasta.c++", "-o", "fasta.c++.o"],
   ["fasta.c++.o", "-o", "fasta", "-lpthread"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-std=c++17", "knucleotide.c++", "-o", "knucleotide.c++.o"],
   ["knucleotide.c++.o", "-o", "knucleotide", "-lpthread"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-mfpmath=sse", "-msse3", "-fopenmp", "mandelbrot.c++", "-o", "mandelbrot.c++.o"],
   ["mandelbrot.c++.o", "-o", "mandelbrot", "-fopenmp"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-mfpmath=sse", "-msse3", "nbody.c++", "-o", "nbody.c++.o"],
   ["nbody.c++.o", "-o", "nbody"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-std=c++14", "-g", "pidigits.c++", "-o", "pidigits.c++.o"],
   ["pidigits.c++.o", "-o", "pidigits", "-lgmp", "-lgmpxx"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-std=c++17", "-fopenmp", "-flto", "regexredux.c++", "-o", "regexredux.c++.o"],
   ["regexredux.c++.o", "-o", "regexredux", "-fopenmp", "-lpcre"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-std=c++11", "-mtune=native", "-mfpmath=sse", "-msse2", "revcomp.c++", "-o", "revcomp.c++.o"],
   ["revcomp.c++.o", "-o", "revcomp", "-pthread"],
   ["-c", "-pipe", "-O3", "-fomit-frame-pointer", "-march=native", "-mfpmath=sse", "-msse3", "-fopenmp", "spectralnorm.c++", "-o", "spectralnorm.c++.o"],
   ["spectralnorm.c++.o", "-o", "spectralnorm", "-fopenmp"],
]
